[workspace]
members = [
  "jdsp",
  "circular_buffer",
  "iir_biquad_filter",
  "oversampler",
  "adaa_nl", "envelope", "window", "dc_filter", 
]

[profile.release]
opt-level = 3
strip = "none"
codegen-units = 1
lto = "fat" 


