[package]
name = "circular_buffer"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.4"

[target.'cfg(target_arch = "aarch64")'.dependencies]
apple-sys = { version = "0.2.0", features = ["Accelerate"] }

[profile.release]
debug = true

